#! /bin/sh

sxhkd &

bspc monitor DisplayPort-4 -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-3 -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-5 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.50
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true
