-- require'lspconfig'.rust_analyzer.setup {
--   settings = {
--     cargo = {
--       allFeatures = true;
--     };
--     checkOnSave = {
--       allFeatures = true;
--       command = "clippy";
--       enable = true;
--     };
--   };
-- }
