#!/bin/sh

gen-xresources > $HOME/.Xresources

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
[[ -f $userresources ]] && xrdb -merge -I$HOME $userresources
[[ -f $usermodmap ]] && xmodmap $usremodmap

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# set up key bindings
xbindkeys

case $2 in
    "i3")       exec i3 ;;
    "openbox")  exec openbox-session ;;
    *)          exec i3 ;;
esac
